### ISSUE TITLE
when unhover profile zone, ChangeProfilePicture must be closed

### ISSUE THREAD

**Issue by petreleon** [RodicaMihaelaVasilescu/RM-Messenger#1]
Profile zone means profile picture, status, RM! Voice and Games.
![unhover profile image](https://user-images.githubusercontent.com/13880012/64484380-be494900-d219-11e9-9f73-e547dcc447b8.gif)

**Comment by RodicaMihaelaVasilescu** [comment]
Hi, Petre!

Thank you for reporting this issue. I’ll investigate it soon.

But as you can see, I haven’t finished that section yet, those profile picture buttons are still not functional. When I finish the profile picture settings, I will let you know.

Wish you all the best,
Rodica

**Comment by RodicaMihaelaVasilescu** [comment]
Hi,

Your issue is now fixed.
Thank you for your interest in RM!Messenger.

All the best,
Rodica
